name: Linting and Tests

on:
  pull_request:
    branches:
      - ${{ github.base_ref }}

jobs:
  linters:
    name: Linting
    uses: KsQRooW/test-workflow/.github/workflows/linters.yml@main


  tests:
    name: Testing
    needs: linters
    uses: KsQRooW/test-workflow/.github/workflows/tests.yml@main
